- hosts: all
  become: true
  tasks: 
     - name: create new deployment
       shell: "kubectl apply -f /home/user-prarora/Deployment.yml"
     - name: create new service
       shell: "kubectl apply -f /home/user-prarora/Service.yml"