kind: Deployment
apiVersion: apps/v1
metadata:
   name: pradhyumanarora
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: pradhyumanarora
   template:
      metadata:
        labels:
          app: pradhyumanarora
      spec:
       containers:
        - name: pradhyumanarora
          image: pradhyumanarora/pipeline-demo
          imagePullPolicy: Always
          ports:
          - containerPort: 80