kind: Service                             
apiVersion: v1
metadata:
  name: pradhyumanarora
  labels:
    app: pradhyumanarora
spec:
  ports:
    - port: 8080                              
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: pradhyumanarora                    
  type: LoadBalancer                   